# Generated by Django 3.0.3 on 2020-04-10 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calisanlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=30)),
                ('soyad', models.CharField(max_length=30)),
                ('kullanici_adi', models.CharField(max_length=10)),
                ('sifre', models.CharField(max_length=30)),
                ('calisma_turu', models.CharField(max_length=30)),
                ('departman', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mekanlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mekan_ismi', models.CharField(max_length=120, verbose_name='mekan ismi')),
                ('mekan_adresi', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Yoneticiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=30)),
                ('soyad', models.CharField(max_length=30)),
                ('kullanici_adi', models.CharField(max_length=10)),
                ('sifre', models.CharField(max_length=30)),
                ('calisma_turu', models.CharField(max_length=30)),
                ('departman', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Planlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_tarihi', models.DateField(verbose_name='plan tarihi')),
                ('giris_saati', models.TimeField(verbose_name='Giriş Saati')),
                ('sure', models.DurationField(verbose_name='Süre')),
                ('cikis_saati', models.TimeField(verbose_name='Çıkış Saati')),
                ('plan_gunu', models.CharField(max_length=30)),
                ('calisan', models.ManyToManyField(to='webProject.Calisanlar')),
                ('mekan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webProject.Mekanlar')),
                ('yonetici', models.ManyToManyField(to='webProject.Yoneticiler')),
            ],
        ),
    ]
