# Generated by Django 3.0.4 on 2020-04-12 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planlar',
            name='calisan',
        ),
        migrations.RemoveField(
            model_name='planlar',
            name='mekan',
        ),
        migrations.RemoveField(
            model_name='planlar',
            name='yonetici',
        ),
        migrations.DeleteModel(
            name='Mekanlar',
        ),
        migrations.DeleteModel(
            name='Planlar',
        ),
    ]
