# Generated by Django 3.0.4 on 2020-04-12 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webProject', '0002_auto_20200413_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mekanlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mekan_ismi', models.CharField(max_length=120, verbose_name='mekan ismi')),
                ('mekan_adresi', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Planlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_tarihi', models.DateField(verbose_name='plan tarihi')),
                ('giris_saati', models.TimeField(verbose_name='Giriş Saati')),
                ('sure', models.DurationField(verbose_name='Süre')),
                ('cikis_saati', models.TimeField(verbose_name='Çıkış Saati')),
                ('plan_gunu', models.CharField(max_length=30)),
                ('calisan', models.ManyToManyField(to='webProject.Calisanlar')),
                ('mekan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webProject.Mekanlar')),
                ('yonetici', models.ManyToManyField(to='webProject.Yoneticiler')),
            ],
        ),
    ]
